### ISSUE TITLE
Outil "Contribuer" : envoyer un mail automatique aux contributeurs quand la PR est mergée

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-base-nationale-covoiturage#118]
Une fois que le producteur a soumis sa contribution > qu'on a vérifié et validé > possible d'envoyer un mail automatique au contributeur avec comme contenu : 
"Bonjour, 
Votre demande de mise à jour a bien été prise en compte et a été intégrée à la Base nationale des lieux de covoiturage. L'équipe de Transport.data.gouv.fr vous en remercie.
Pour toute question, n'hésitez pas à nous contacter à l'adresse : contact@transport.beta.gouv.fr.

Bien à vous,"

**Comment by AurelienC** [comment]
Suite aux évolutions prévues pour contribuer à la BNLC, via data.gouv.fr, mettant fin à moyen terme à l'outil "Contribuer", je ferme cette PR.
