### ISSUE TITLE
Outils "Contribuer" : L'ajouter à la liste des outils de la page d'accueil du PAN

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-base-nationale-covoiturage#119]
Serait il possible d'intégrer l'outil Contribuer à la plateforme et de l'ajouter à la liste des outils de la page d'accueil de transport.data.gouv.fr ?

**Comment by AurelienC** [comment]
Suite aux évolutions prévues pour contribuer à la BNLC, via data.gouv.fr, mettant fin à moyen terme à l'outil "Contribuer", je ferme cette PR.
