### ISSUE TITLE
doc sur l'utilisation des PR pour alimenter la base

### ISSUE THREAD

**Issue by vfabry** [etalab/transport-base-nationale-covoiturage#122]
Bonjour,
Je n'ai aps bien compris comment alimenter la base en utilsant une PR. Il y a une doc quelque part ?
Par ailleur, le lien sur la page d'accueil renvoie une 404 :
![image](https://user-images.githubusercontent.com/15424976/191976517-7c6d3a7b-1da9-4f3e-9a0b-6daffa68cbd0.png)

Vincent Fabry
administrateur Géo2France

**Comment by Miryad3108** [comment]
Bonjour @vfabry 
Navrée pour notre réponse tardive. Vous pouvez faire une PR en passant par l'outil [Contribuer](https://contribuer.transport.data.gouv.fr/).
Une documentation est disponible [ici](https://doc.transport.data.gouv.fr/producteurs/lieux-de-covoiturage/contribuer-a-la-base-nationale-des-lieux-de-covoiturage#utiliser-loutil-daide-a-la-contribution-contribuer). N'hésitez pas à revenir vers nous si ce n'est pas clair.

Merci de nous avoir averti pour l'erreur 404, nous allons corriger cela.
