### ISSUE TITLE
Ajout de CircleCI

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-base-nationale-covoiturage#2]
Ca serait pratique d'au minimum rebrancher une vérification sur schema.data.gouv avant d'autoriser un merge, pour éviter les blagues.

Je n'ai jamais mis ça en place, mais ça m’intéresserait de voir comment on fait si on peut s'y mettre ensemble @antoine-de et @thbar .

**Comment by fchabouis** [comment]
Finalement je m'en suis sorti. Vu que je suis néophyte en la matière n'hésitez pas à jeter un oeil au dossier .circleci pour me dire si ça vous semble fait dans les règles de l'art ci. @antoine-de @thbar

**Comment by antoine-de** [comment]
yep ca me semble bien, t'aurais pu faire un oneliner à coup de `jq` mais franchement la ca fait le taff, c'est top

par contre ton log ne doit pas s'afficher si ? si tu configures pas les logs il ne sortira rien je pense (et autant utiliser `print` la je pense
