### ISSUE TITLE
Message d'erreur incomplet dans les tests d'intégration de datasets.csv

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-base-nationale-covoiturage#202]
Le champ de remplacement n'est pas interprêté → `{FILENAME}`

![image](https://github.com/etalab/transport-base-nationale-covoiturage/assets/4528670/6f1d66fb-9266-436f-8afa-b91f287968e9)

**Comment by AurelienC** [comment]
Si de plus ça peut indiquer l'URL en doublon, ce serait parfait

**Comment by AntoineAugusti** [comment]
done https://github.com/etalab/transport-base-nationale-covoiturage/commit/15898e9f49fa58b946b2c67273df179bd784461f
