### ISSUE TITLE
Les PR générées contiennent un lien vers d'anciennes PR

### ISSUE THREAD

**Issue by thbar** [etalab/transport-base-nationale-covoiturage#53]
(peut-être que Francis est au courant et que c'est en lien avec le fonctionnement connu du bot, on en parlera avec lui à son retour de congés)

En travaillant aujourd'hui avec @Miryad3108, nous avons cherché à comprendre comment des suppressions non désirées s'étaient retrouvées mergées (voir enquête https://github.com/etalab/transport-base-nationale-covoiturage/pull/50).

Nous avons fait une PR (#52) via l'outil "contribuer": si on retrouve bien les modifications souhaitées dans 1fb3b20, on voit également un "merge pull request #15 from etalab/main" qui est sans rapport et déroutant pour la vérification (c'est une PR sans rapport qui date du 20 janvier, pour le département de la somme).

On retrouve ce point dans les PR suivantes:
- https://github.com/etalab/transport-base-nationale-covoiturage/pull/49 (qui "pointe" vers #14, mais le résultat final est malgré tout apparemment le bon)
- https://github.com/etalab/transport-base-nationale-covoiturage/pull/48 (qui "pointe" vers #13 du 18 janvier)
- https://github.com/etalab/transport-base-nationale-covoiturage/pull/47 (qui "pointe" vers #12)

J'ai l'impression qu'à chaque fois, on n'a tout de même que ce qu'on souhaite, mais le suivi dans le temps est perturbé, il faudra qu'on enquête.

**Comment by Miryad3108** [comment]
@fchabouis il me semble que tu réglé ce problème ?

**Comment by AurelienC** [comment]
Pb réglé.
